services:
  - type: web
    name: startupvault-api
    runtime: java
    buildCommand: chmod +x mvnw && ./mvnw package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar

    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: CORS_ORIGINS
        sync: false
      - key: PORT
        value: "8080"
